package entity;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.student_name
     *
     * @mbggenerated
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_list.student_number
     *
     * @mbggenerated
     */
    private Integer studentNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.id
     *
     * @return the value of student_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.id
     *
     * @param id the value for student_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.student_name
     *
     * @return the value of student_list.student_name
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.student_name
     *
     * @param studentName the value for student_list.student_name
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_list.student_number
     *
     * @return the value of student_list.student_number
     *
     * @mbggenerated
     */
    public Integer getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_list.student_number
     *
     * @param studentNumber the value for student_list.student_number
     *
     * @mbggenerated
     */
    public void setStudentNumber(Integer studentNumber) {
        this.studentNumber = studentNumber;
    }

    private  Teacher teacher;

    public Teacher getTeacher() {
        return teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
}